# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c60f0160a0c2d73bd7416ac9c8e8f1f1aac8a024e54ffa94f7fc3184fd5343e098939fe78851dd8d66780cbb50bb56756628f471e89df67f67358140950484d6

  sms:
    trxn:
      user_name: 'manager.employeeapp@gmail.com'
      api_hash: 'a44321883edc58360dc6f96c2e983148b225c951'
      sender_name: 'TXTLCL'
test:
  secret_key_base: 4caba7e566b08dc3673aaff1c58656e9fb1736d115f11b87184a8ef26da0d48f13409116ffebac30039ecb2c34d3bbc4de1e98dc27503716407797a56f316032

  sms:
    trxn:
      user_name: 'something@example.com'
      api_hash: '123456fafafaf'
      sender_name: 'TXTLCL'
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
